set_countdown:
    description: Sets Count Down Time
    fields:
        entity_id:
            description: Time To entity
            example: "sensor.ac_time_to_on"
        minutes:
            description: Minutes until action
            example: "60"