set_freshair:
    description: Sets Fresh Air Status
    fields:
        entity_id:
            description: Primary climate entity
            example: "climate.ac"
        status:
            description: Free Air Status
            example: "on"