name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Pull Home Assistant Container
        run: docker pull homeassistant/home-assistant:beta
      - name: Run hassfest
        run: |
          integration=$(python3 -m scripts.helpers.integration_path)
          domain=$(python3 -m scripts.helpers.domain)
          docker run --entrypoint=""  -v "$integration":"/$domain" \
            homeassistant/home-assistant:beta python3 -m \
            script.hassfest --action validate --integration-path "/$domain"
